In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf

In [2]:
X = np.arange(1,100,2)
Y = np.arange(0,100,2)
X, Y

(array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
        35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
        69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99]),
 array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
        34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
        68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98]))

In [3]:
X = tf.constant(X)
Y = tf.constant(Y)
X,Y

(<tf.Tensor: shape=(50,), dtype=int64, numpy=
 array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
        35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
        69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])>,
 <tf.Tensor: shape=(50,), dtype=int64, numpy=
 array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
        34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
        68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])>)

In [15]:
tf.random.set_seed(42)

model = tf.keras.Sequential([tf.keras.layers.Dense(100, input_shape=[1])])

model.compile(loss=tf.keras.losses.mae,
              optimizer=tf.keras.optimizers.legacy.SGD(),  
              metrics=["mae"])

model.fit(X, Y, epochs=50)


Epoch 1/50
2/2 [==============================] - 0s 5ms/step - loss: 49.0416 - mae: 49.0416
Epoch 2/50
2/2 [==============================] - 0s 2ms/step - loss: 48.5555 - mae: 48.5555
Epoch 3/50
2/2 [==============================] - 0s 1ms/step - loss: 48.0721 - mae: 48.0721
Epoch 4/50
2/2 [==============================] - 0s 2ms/step - loss: 47.5844 - mae: 47.5844
Epoch 5/50
2/2 [==============================] - 0s 2ms/step - loss: 47.1029 - mae: 47.1029
Epoch 6/50
2/2 [==============================] - 0s 4ms/step - loss: 46.6124 - mae: 46.6124
Epoch 7/50
2/2 [==============================] - 0s 1ms/step - loss: 46.1022 - mae: 46.1022
Epoch 8/50
2/2 [==============================] - 0s 1ms/step - loss: 45.5872 - mae: 45.5872
Epoch 9/50
2/2 [==============================] - 0s 1ms/step - loss: 45.0786 - mae: 45.0786
Epoch 10/50
2/2 [==============================] - 0s 2ms/step - loss: 44.5773 - mae: 44.5773
Epoch 11/50
2/2 [==============================] - 0s 2ms/step - loss

In [ ]:
model_2 = tf.keras.layers.Sequential([tf.keras.layers.Dense(100)])